version: "3.7"
services:
  pddl:
    image: pddl:latest
    build: ./
    container_name: pddl
    hostname: pddl
    stdin_open: true
    tty: true
    volumes: 
      - ./src:/planning/src
    ports:
      - 80:80
